# Generated by Django 4.2.7 on 2023-11-20 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('job_title', models.CharField(max_length=250)),
                ('bio', models.TextField(max_length=500)),
                ('employer_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('job_description', models.TextField(max_length=1000)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(max_length=250)),
                ('duties', models.TextField(max_length=1000)),
                ('project_name', models.CharField(max_length=250)),
                ('start_date_of_project', models.DateField(blank=True, null=True)),
                ('end_date_of_project', models.DateField(blank=True, null=True)),
                ('project_description', models.TextField(max_length=1000)),
                ('university_name', models.CharField(max_length=250)),
                ('start_date_university', models.DateField(blank=True, null=True)),
                ('end_date_university', models.DateField(blank=True, null=True)),
                ('skill_name', models.CharField(max_length=250)),
                ('skill_description', models.TextField(max_length=1000)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
