# Generated by Django 4.2.7 on 2023-11-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='end_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='end_date_of_project',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='end_date_university',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_date_of_project',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_date_university',
            field=models.CharField(blank=True, null=True),
        ),
    ]
