# Generated by Django 4.2.7 on 2023-11-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_template',
            field=models.CharField(choices=[('Simple Resume', 'Simple Resume'), ('Modern Resume', 'Modern Resume')], default='_'),
        ),
    ]
